import Head from 'next/head'
import Image from 'next/image'
import ZI_Doc from '../components/ZI_Doc'

export default function Home() {
  return (
    <div>
      <Head>
        <title>ZI-DOC@ZIMOGROUP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
     <ZI_Doc/>
      </main>

    
    </div>
  )
}
